apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: 
  name: 
contexts:
- context:
    cluster: do-nyc1-k8s-aula
    user: do-nyc1-k8s-aula-admin
  name: do-nyc1-k8s-aula
current-context: do-nyc1-k8s-aula
kind: Config
preferences: {}
users:
- name: 
  user:
    token: 
