apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEF6TWpJeQpNVFU1TlRoYUZ3MDBOVEF6TWpJeU1UVTVOVGhhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDbXZZK3JqSTd0RFFCbkxSRnk1cGdiVElWWjdicmJRUHRKOWgyVlUrdHUwSGxFYkZJNgpKMS9pN2ZuUlY2alIvR1JnYzVXem1XRmlBQ0xsL3hBVUtoRnNrZ2FKakVVRVRKUnJXeW04c2EvOTJLdEl5amhCCkxzN2dpcllZZkJEcTZ3MG5kMzdnVTZRemdkZHlZOEZ3RUFBTFZDK084ekNWVUt2bHFZcFpvb2kwMnZsbzdnejIKd0F6RFVtWWNTWHdURmFRZTJEVGNGSzJBTWpRdlVyTXN2V09LVmJzRkR3UDA0d2JSWk53aTRwcmFFSXFYQXhxdAp0d0YweXhLVHNUR3pNdWJlZ0w4YTZYVGVhODR0N1g0dFplOFBsZG9iZTRMS3hQK0wzWlE3ZWJtNXd2Y1N3blhHCndRYmxuYkIydFdRNFp6QThibDMxblYycnJkQ2VOMk12bkNBcEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNpbEUrVlFURzhxVkptQUlncwpGS21CWnZvYUpUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFYK0lKUHQxRVY2dGtjUjBPa3FVbGxBZGpTZGNJCmdyYy8zd0d0aEVTbFVlTFhVQVplOWcyMXZvZGpkZGhnZlhUQ0VhemJQajM0U2ZkT2Z0QjV5VU12eklEbVlSc0YKMEVHR0Frd2FSek9wV25UbjR0K01IbVJNeFVZM1k5aEpsRkV3b0s2VnNvVjFzR1lZMkF1emgreFFxU0RIVmxKLwo0UTN1MXphR1VaejlrUE9Gdmh3OCtqWVBPb3R4dldqS0lwNUhWaXdDc0Z1OVJxdGNvZHMzcGgvdmFYNFlvM2RVCjQ3WjhsT2R4YTAraEN4VWpGb0JYbmxLUlBLaW5sdW9LL1ZkeHFqWkdxWHh1dnVuWVpydVM0ZXFXM1JlREIzL24KUDQyUjB2U2t3QnJxaC9uY2tubm1Fblh0dzNIelN0S2JkY1EyOElPbEgvaU9oTGxSSzNQdnp5dTFyQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://7019ec4c-6cf9-4b47-b523-940d33020617.k8s.ondigitalocean.com
  name: do-nyc1-k8s-aula
contexts:
- context:
    cluster: do-nyc1-k8s-aula
    user: do-nyc1-k8s-aula-admin
  name: do-nyc1-k8s-aula
current-context: do-nyc1-k8s-aula
kind: Config
preferences: {}
users:
- name: do-nyc1-k8s-aula-admin
  user:
    token: dop_v1_112a21ce9e11c81dc32c813c27be5afe6161280c55c72a7898c84c94ad9d8d4c
